### ISSUE TITLE
Quick update of atom with a previous value is ignored

### ISSUE THREAD

**Issue by lisss** [grammarly/focal#24]
When you quickly update an atom with a previous value right after updating with a new one - the last change is ignored
The code sample can be found [here](https://codesandbox.io/s/47wnlm6r9)

**Comment by valentyng** [comment]
It looks like the issue is here:
- `RenderOne` https://github.com/grammarly/focal/blob/master/src/react/react.ts#L388-L389
- `RenderMany` https://github.com/grammarly/focal/blob/master/src/react/react.ts#L487-L488 

According to the documentation (https://reactjs.org/docs/react-component.html#setstate): 
>Think of setState() as a request rather than an immediate command to update the component.

`liftedComponent.setState()` doesn't update `liftedComponent.state` immediately.

So, every new `renderCache` is compared to the initial value, and if they are equal, the state isn't updated.

**Comment by valentyng** [comment]
A possible solution is moving `structEq(liftedComponent.state.renderCache, renderCache)` to `shouldComponentUpdate` (https://github.com/grammarly/focal/blob/master/src/react/react.ts#L116).

However, I'm not sure about performance here.
@blacktaxi what do you think?

**Comment by blacktaxi** [comment]
That seems to be a good catch! Let me take some time to debug this. Not sure about moving `structEq` to `shouldComponentUpdate`, intuitively it indeed seems to ought to affect performance.

Another obvious solution could be to use the `this.setState(prevState => ...)` overload and perform the `structEq` call in the callback.

**Comment by oleksiilevzhynskyi** [comment]
@blacktaxi `this.setState(prevState => prevState)` triggers render. It looks like it doesn't make sense to use `structEq` here. Code - https://codesandbox.io/s/0ol9q3q38w

**Comment by blacktaxi** [comment]
Added a repro and tracking this in #27 now
