### ISSUE TITLE
`keyof` based lenses?

### ISSUE THREAD

**Issue by polytypic** [grammarly/focal#3]
I'm not deeply familiar with TypeScript, but have you considered using [`keyof`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html) based [lenses](https://gist.github.com/mitaki28/ad39a69ab4fa73c99a822c0c3abc99dd) for accessing properties?

**Comment by blacktaxi** [comment]
Yes, in fact I have! It seems to be the way to go, because the current hack with parsing "property expressions" is really just a hack.

Looking at the gist you linked, I even came up with a similar idea to hack around TS 2.1's limitation of inferring either all or none of the type parameters for a single function application (https://gist.github.com/mitaki28/ad39a69ab4fa73c99a822c0c3abc99dd#file-lens-ts-L36). Maybe we don't need to do this in TS 2.2 anymore? I'll have to check.

I haven't implemented `keyof` lenses yet because of the syntax complication that this hack incurs, but maybe it isn't so bad after all.

Another thing that's been bothering me is this:

```typescript
type O = { [k: string]: number }
type K = keyof O
type V = O[K] 
```

Here the type of `V` is `number`, while at runtime the value can also be `undefined`. Not sure it's a problem that we can (and should be trying to) solve, but a `keyof` based lens in the case of key type `K` and object type `O` (as in this example), will give a `Lens<O, V>`, where more honestly it should be a `Prism<O, V>`.

**Comment by blacktaxi** [comment]
Tracking this in #11 now.
