### ISSUE TITLE
Replace regex in Lens.prop with Proxy

### ISSUE THREAD

**Issue by texastoland** [grammarly/focal#34]
Just stopping through reading your tutorial.

### Before

https://github.com/grammarly/focal/blob/271e37de4a361ab9ca81ff5ef9035d9b59d8e75e/src/lens/json.ts#L68-L72

### After

```typescript
type PropPath = (string | number | symbol)[]

function extractPropertyPath<Arg, Ret>(getter: PropExpr<Arg, Ret>): PropPath {
  const errorMessage = `Expected a property expression, got "${getter}"...`
  const props: PropPath = []
  getter(new Proxy(Object.create(null), {
    get(_, prop, proxy) {
      if (prop === Symbol.toPrimitive) {
        throw TypeError(errorMessage)
      }
      props.push(prop)
      return proxy
    },
  }) as Arg)
  return props
}
```

### Demo

https://codepen.io/anon/pen/ejeWoL?editors=0011#0

**Comment by blacktaxi** [comment]
Thanks, this is quite clever! I like it.

It would be perfect if there was a way to restrict what kind of expression can you put in a `getter` at the type level, so that invalid getters like `x => x[5]++` don't compile.

Currently I think the best way to do lenses is to use another overload that is using the `keyof` types (added in #11 ). Shame the tutorial still hasn't been updated to reflect that... However, until the support for `PropExpr` is removed, maybe it makes sense to improve its implementation.

**Comment by texastoland** [comment]
Clever idea with nullary application and chaining atoms to eliminate generic annotations too. I borrowed my idea from Immer. The getter syntax inspired me because it looks deceptively imperative. I agree though that invalid getters might surprise someone trying to make a computed property. `x => x[5]++` throws a `TypeError` though because you can't increment my Proxy. You can trap nearly anything a user might try and throw a custom error without losing the stack trace. I edited my snippet and linked pen.
