### ISSUE TITLE
Publish Atom/Lens-only version

### ISSUE THREAD

**Issue by magneticflux-** [grammarly/focal#68]
I love the concept of `Atom` and wish I could use it on non-React projects. Unfortunately, using this library forces me to pull in all of React to compile.

**Comment by magneticflux-** [comment]
@rileyatodd it seems like you had a similar idea about 1.5 years ago: https://github.com/rileyatodd/focal.

Would you be open to updating that fork and possibly including my PR #70?

**Comment by rileyatodd** [comment]
@magneticflux- unfortunately I don't have much free time these days to do so. From what I remember though, all I did was remove stuff until the tests passed again (and not run the example tests because they all depend on react.) If I were you I'd just make a new fork from the current master and remove the react dependencies rather than trying to update my old fork.

Best of luck!

**Comment by magneticflux-** [comment]
@rileyatodd I've cherry-picked your original commits, rebased them onto the current master, and merged my PR here: https://github.com/magneticflux-/focal/tree/remove-react-dependencies

Would you allow me to publish versions under `focal-sans-react` on NPM https://www.npmjs.com/package/focal-sans-react?

**Comment by blacktaxi** [comment]
Hi all! Thanks for looking into this. I wanted to let you know that we're looking into publishing the atom bits as a separate package. I don't have an ETA, but I know that @oleksiilevzhynskyi is working on that – maybe he could provide more details.

**Comment by rileyatodd** [comment]
@magneticflux- I'll wait to see what @oleksiilevzhynskyi comes up with. It looks like `focal-atom` will be the name of the new package but if that doesn't end up happening I can look into turning over the `focal-sans-react` name on NPM to someone that is more actively using it 🙂
